### ISSUE TITLE
Bypass trusted domain check when using redirect API

### ISSUE THREAD

**Issue by surli** [xwikisas/application-office365#14]
XWiki 13.3RC1 and 12.10.7 introduced a security mechanism to avoid redirecting users to untrusted domains. Extension which uses this API can still bypass the check by setting `bypassDomainSecurityCheck` to true in the execution context before using the redirect API, to avoid problems if administrators don't properly set it up.

**Comment by polx** [comment]
Fixed in [here](https://github.com/xwikisas/application-office365/commit/87c75abcbf23f621e069731a9631a2a4e6db7630).
