### ISSUE TITLE
Add extensions components in the descriptor

### ISSUE THREAD

**Issue by tmortagne** [xwikisas/application-office365#15]
Add the metadata defined by https://jira.xwiki.org/browse/XCOMMONS-2189.

**Comment by polx** [comment]
Thanks for suggesting and fixing this.
Just for us to know: What components are needed to be described here?
- macros in XWiki objects
- also the components inside components.txt which refer to java components? (I guess this very project doesn't have any)
- also the internal components (for which role and class match)? (also none here)
paul

**Comment by polx** [comment]
@tmortagne : would this be the right tool to get informed on just about any components out in the world (of a maven repo) that implements a given role?
