### ISSUE TITLE
Can't connect XWiki to Office365

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-office365#17]
Steps to reproduce:
1. Follow the steps from https://qa.xwikisas.com/xwiki/bin/view/Office365%20Integration%20%28Pro%29/Connect%20XWiki%20to%20Office365

Expected results: Office365 asks to login.

Actual results: After performing the last step "Create a new page and use the {{office365 /}} macro" no option appears to login with Office365.

On Cloud when searching for something the admin gets 
"Personal Drive
Error searching Office 365:  https://graph.microsoft.com/v1.0/me/drive/search(q='test')"

![CloudOffice365](https://user-images.githubusercontent.com/40691112/132708150-cab1963a-7891-4857-b13f-e40430e884ac.jpg)

On local instance:

![Office365-1](https://user-images.githubusercontent.com/40691112/132708720-9240bcc4-d757-48ed-8850-7f94cb415a24.jpg)

Tested with Cloud (13.4.3) and local with XWiki 13.7 and 12.10.9

**NOTE**
Locally a change has to be made in xwiki properties for the login request to appear when accessing the page with the "{{office365 /}}"

#-# [Since 13.3RC1]
#-# [Since 12.10.7]
#-# Define a list of trusted domains that can be used in the wiki for performing requests or redirections even if
#-# the wiki does not use it. Domains are listed without http and separated with a comma in the list. Subdomains can be
#-# specified.
#-# Example of accepted value: foo.acme.org,enterprise.org
#-#
#-# By default the list of trusted domains is empty:
url.trustedDomains=login.windows.net

**Comment by polx** [comment]
Fixed.
