### ISSUE TITLE
Microsoft app registration not available anymore

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-office365#20]
Hi, 

While testing the Office365 Integration app and trying to register it on the link provided on the dedicated page on the wiki - https://apps.dev.microsoft.com/ , I noticed that there is a message on the Microsoft site page:
"Application registrations portal is no longer available to register and manage converged applications. We recommend that ​you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. ​"

![image](https://user-images.githubusercontent.com/36840106/166640339-65fe20d9-e91e-4af0-8092-b0df22635670.png)

There is also a blog post about this change: https://devblogs.microsoft.com/microsoft365dev/deprecation-of-app-registrations-legacy-experience-and-the-application-registration-portal-apps-dev-microsoft-com/ :
"After December 15, 2019, users with Azure AD accounts will no longer be able to register and manage applications in the Application Registration Portal. " and
"After March 1, 2020, users will no longer be able to register and manage applications in the App registrations (Legacy) experience."

Thus, please remove the mention "or on this [microsoft app registration web site](https://apps.dev.microsoft.com/)" from this page content https://server/xwiki/bin/view/Office365/ .

![image](https://user-images.githubusercontent.com/36840106/166640046-7da3caf0-205a-4ee4-9818-3a6d4f4dd043.png)

**Comment by AndreeaChi** [comment]
Or add the new registration option from the Azure Portal.

Proposed change:
This can be done in the [Azure Portal](https://portal.azure.com/), by registering a new application through the **App registrations** service.

**Comment by mflorea** [comment]
@AndreeaChi I applied your suggestion. Thanks.
